### ISSUE TITLE
关于飞雪无情博客超链接的错误 

### ISSUE THREAD

**Issue by rujews** [udpsec/maupassant-hugo-v2#1]
README文档里关于`飞雪无情的博客`的超链接打不开，我看了下是URL错了，最后多了一个o。
你可以使用我的博客的地址[http://www.flysnow.org/](http://www.flysnow.org/),或者github的地址[https://github.com/rujews/maupassant-hugo](https://github.com/rujews/maupassant-hugo)。

有时间帮忙修正下，多谢。

**Comment by udpsec** [comment]
> README文档里关于`飞雪无情的博客`的超链接打不开，我看了下是URL错了，最后多了一个o。
> 你可以使用我的博客的地址http://www.flysnow.org/,或者github的地址https://github.com/rujews/maupassant-hugo。
> 
> 有时间帮忙修正下，多谢。

已修正
